//course
export const COURSE_LIST_WRETCH_LOADED = 'COURSE_LIST_WRETCH_LOADED';
export const COURSE_LIST_WRETCH_LOADING = 'COURSE_LIST_WRETCH_LOADING';
export const COURSE_LIST_WRETCH_FAIL = 'COURSE_LIST_WRETCH_FAIL';
export const COURSE_LIST_TOOGLE_MODAL_CREATE_COURSE = 'COURSE_LIST_TOOGLE_MODAL_CREATE_COURSE';
export const COURSE_LIST_TOOGLE_MODAL_DELETE_COURSE = 'COURSE_LIST_TOOGLE_MODAL_DELETE_COURSE';
export const COURSE_LIST_DELETE_COURSE = 'COURSE_LIST_DELETE_COURSE';
export const COURSE_LIST_WRETCH_CREATE_COURSE = 'COURSE_LIST_WRETCH_CREATE_COURSE';
export const COURSE_CREATE_NO_NAME_VALIDATED = 'COURSE_CREATE_NO_NAME_VALIDATED';
export const COURSE_CREATE_NO_DESCRIPTION_VALIDATED = 'COURSE_CREATE_NO_DESCRIPTION_VALIDATED';
export const COURSE_CREATE_NO_DURATION_VALIDATED = 'COURSE_CREATE_NO_DURATION_VALIDATED';
export const COURSE_CREATE_INPUT_DATA_NEW_COURSE = 'COURSE_CREATE_INPUT_DATA_NEW_COURSE';
export const COURSE_CREATE_CREATE_MODAL_UNVALIDATE_INPUT_NAME = 'COURSE_CREATE_CREATE_MODAL_UNVALIDATE_INPUT_NAME';
export const COURSE_CREATE_CREATE_MODAL_UNVALIDATE_INPUT_DESCRIPTION = 'COURSE_CREATE_CREATE_MODAL_UNVALIDATE_INPUT_DESCRIPTION';
export const COURSE_CREATE_CREATE_MODAL_UNVALIDATE_INPUT_DURATION = 'COURSE_CREATE_CREATE_MODAL_UNVALIDATE_INPUT_DURATION';

//user
export const USER_LIST_WRETCH_LOADING = 'USER_LIST_WRETCH_LOADING';
export const USER_LIST_WRETCH_LOADED = 'USER_LIST_WRETCH_LOADED';
export const USER_LIST_WRETCH_FAIL = 'USER_LIST_WRETCH_FAIL'; 
export const  USER_TO_VIEW_WRETCH_LOADING = "USER_TO_VIEW_WRETCH_LOADING";
export const  USER_TO_VIEW_WRETCH_LOADED = "USER_TO_VIEW_WRETCH_LOADED";
export const  USER_TO_VIEW_WRETCH_FAIL = "USER_TO_VIEW_WRETCH_FAIL";
export const USER_TO_EDIT_WRETCH_LOADING = "USER_TO_EDIT_WRETCH_LOADING";
export const USER_TO_EDIT_WRETCH_LOADED = "USER_TO_EDIT_WRETCH_LOADED";
export const USER_TO_EDIT_WRETCH_FAIL = "USER_TO_EDIT_WRETCH_FAIL";

//notifications
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';