//course
export const COURSE_LIST_WRETCH_LOADED = 'COURSE_LIST_WRETCH_LOADED';
export const COURSE_LIST_WRETCH_LOADING = 'COURSE_LIST_WRETCH_LOADING';
export const COURSE_LIST_WRETCH_FAIL = 'COURSE_LIST_WRETCH_FAIL';
export const COURSE_LIST_OPEN_MODAL_CREATE_COURSE = 'COURSE_LIST_OPEN_MODAL_CREATE_COURSE';
export const COURSE_LIST_CLOSE_MODAL_CREATE_COURSE = 'COURSE_LIST_CLOSE_MODAL_CREATE_COURSE';
export const COURSE_LIST_OPEN_MODAL_DELETE_COURSE = 'COURSE_LIST_OPEN_MODAL_DELETE_COURSE';
export const COURSE_LIST_CLOSE_MODAL_DELETE_COURSE = 'COURSE_LIST_CLOSE_MODAL_DELETE_COURSE';
export const COURSE_LIST_DELETE_COURSE = 'COURSE_LIST_DELETE_COURSE';
export const COURSE_LIST_WRETCH_CREATE_COURSE = 'COURSE_LIST_WRETCH_CREATE_COURSE';
export const COURSE_CREATE_NO_NAME_VALIDATED = 'COURSE_CREATE_NO_NAME_VALIDATED';
export const COURSE_CREATE_NO_DESCRIPTION_VALIDATED = 'COURSE_CREATE_NO_DESCRIPTION_VALIDATED';
export const COURSE_CREATE_NO_DURATION_VALIDATED = 'COURSE_CREATE_NO_DURATION_VALIDATED';
export const COURSE_CREATE_INPUT_DATA_NEW_COURSE = 'COURSE_CREATE_INPUT_DATA_NEW_COURSE';
export const COURSE_CREATE_CREATE_MODAL_UNVALIDATE_INPUT_NAME = 'COURSE_CREATE_CREATE_MODAL_UNVALIDATE_INPUT_NAME';
export const COURSE_CREATE_CREATE_MODAL_UNVALIDATE_INPUT_DESCRIPTION = 'COURSE_CREATE_CREATE_MODAL_UNVALIDATE_INPUT_DESCRIPTION';
export const COURSE_CREATE_CREATE_MODAL_UNVALIDATE_INPUT_DURATION = 'COURSE_CREATE_CREATE_MODAL_UNVALIDATE_INPUT_DURATION';

//course-edition
export const COURSE_EDITION_WRETCH_LOADING = 'COURSE_EDITION_WRETCH_LOADING';
export const COURSE_EDITION_WRETCH_LOADED = 'COURSE_EDITION_WRETCH_LOADED';
export const COURSE_EDITION_WRETCH_FAIL = 'COURSE_EDITION_WRETCH_FAIL';
export const COURSE_EDITION_WRETCH_GET_COURSE_BY_ID_LOADED = 'COURSE_EDITION_WRETCH_GET_COURSE_BY_ID_LOADED';
export const COURSE_EDITION_ALL_THEMES_IN_COURSE = 'COURSE_EDITION_ALL_THEMES_IN_COURSE';
export const COURSE_EDITION_CHANGE_DISPLAYING_BUTTON_OPEN_PROGRAM_COURSE = 'COURSE_EDITION_CHANGE_DISPLAYING_BUTTON_OPEN_PROGRAM_COURSE';
export const COURSE_EDITION_CHANGE_DISPLAYING_BUTTON_OPEN_MATERIALS_COURSE = 'COURSE_EDITION_CHANGE_DISPLAYING_BUTTON_OPEN_MATERIALS_COURSE';

//user
export const USER_LIST_WRETCH_LOADING = 'USER_LIST_WRETCH_LOADING';
export const USER_LIST_WRETCH_LOADED = 'USER_LIST_WRETCH_LOADED';
export const USER_LIST_WRETCH_FAIL = 'USER_LIST_WRETCH_FAIL';
export const USER_TO_VIEW_WRETCH_LOADING = "USER_TO_VIEW_WRETCH_LOADING";
export const USER_TO_VIEW_WRETCH_LOADED = "USER_TO_VIEW_WRETCH_LOADED";
export const USER_TO_VIEW_WRETCH_FAIL = "USER_TO_VIEW_WRETCH_FAIL";
export const USER_TO_EDIT_WRETCH_LOADING = "USER_TO_EDIT_WRETCH_LOADING";
export const USER_TO_EDIT_WRETCH_LOADED = "USER_TO_EDIT_WRETCH_LOADED";
export const USER_TO_EDIT_WRETCH_FAIL = "USER_TO_EDIT_WRETCH_FAIL";
export const USER_EDIT_MODE_WAS_CLOSED = "USER_EDIT_MODE_WAS_CLOSED";
export const USER_IS_SENDING = "USER_IS_SENDING";
export const USER_SENDING_SUCCESS = "USER_SENDING_SUCCESS";
export const USER_REGISTER_MODE_IS_ON = "USER_REGISTER_MODE_IS_ON";

//user page
export const USER_FOR_USER_PAGE_ID ="USER_FOR_USER_PAGE_ID";

//roleSelector
export const CURRENT_USER_IS_LOADING = "CURRENT_USER_IS_LOADING";
export const CURRENT_USER_WAS_LOADED = "CURRENT_USER_WAS_LOADED";
export const CURRENT_USER_ROLE_ID_SELECTED = "CURRENT_USER_ROLE_ID_SELECTED";
export const CLOSE_ROLE_SELECTOR = "CLOSE_ROLE_SELECTOR";
export const TOGGLE_ROLE_SELECTOR = "TOGGLE_ROLE_SELECTOR";
export const ROLE_SELECTOR_PENDING = "ROLE_SELECTOR_PENDING";
export const CURRENT_USER_UNSET = "CURRENT_USER_UNSET"

//App
export const CURRENT_USER_LOGGED_OUT = "CURRENT_USER_LOGOUT";
export const CURRENT_USER_LOGGED_IN = "CURRENT_USER_LOGGED_IN";

//notifications
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';


//group
export const  GROUP_TO_VIEW_WRETCH_LOADING = "GROUP_TO_VIEW_WRETCH_LOADING";
export const  GROUP_TO_VIEW_WRETCH_LOADED = "GROUP_TO_VIEW_WRETCH_LOADED";
export const  GROUP_TO_VIEW_WRETCH_FAIL = "GROUP_TO_VIEW_WRETCH_FAIL";