export enum InputNames {
    Id = "id",
    FirstName = "firstName",
    LastName = "lastName",
    BirthDate = "birthDate",
    Login = "login",
    Phone = "phone",
    UserPic = "userPic",
    Email = "email",
    Password = "password",
    ContractNumber = "contractNumber",
    Roles = "roles",
    CourseName = "name",
    CourseDescription = "description",
    CourseDuration = "duration",
    LessonDescription = "lessonDescription",
    LessonDate = "lessonDate",
    LessonThemesId = "lessonIdThemes",
    LessonRecordLink = "lessonRecordLink"
}
