export enum InputNames {
    Id = "id",
    FirstName = "firstName",
    LastName = "lastName",
    BirthDate = "birthDate",
    Login = "login",
    Phone = "phone",
    UserPic = "userPic",
    Email = "email",
    Password = "password",
    ContractNumber = "contractNumber",
    Roles = "roles",
    HomeworkDescription = "description", 
    HomeworkStartDate= "startDate",
    HomeworkDeadlineDate="deadlineDate",
    HomeworkIsOptional="isOptional",
    HomeworkCourseId="courseId",
    HomeworkGroupId="groupId",
    HomeworkTags ="tags", 
    HomeworkThemes="themes" 
}